# ----------------------------------------------------------------------------
# -                        Open3D: www.open3d.org                            -
# ----------------------------------------------------------------------------
# Copyright (c) 2018-2026 www.open3d.org
# SPDX-License-Identifier: MIT
# ----------------------------------------------------------------------------

import open3d as o3d
import numpy as np
import pytest
import mltest

# Skip all tests if the ml ops were not built.
pytestmark = mltest.default_marks


@mltest.parametrize.ml_gpu_and_torch_cpu
def test_query_pts(ml):

    values0 = mltest.fetch_numpy(
        'https://storage.googleapis.com/isl-datasets/open3d-dev/test/ml_ops/data/query_pts/values0.npy'
    )
    values1 = mltest.fetch_numpy(
        'https://storage.googleapis.com/isl-datasets/open3d-dev/test/ml_ops/data/query_pts/values1.npy'
    )

    sample = 16
    radius = 0.1

    ans = mltest.run_op(ml, ml.device, True, ml.ops.ball_query, values0,
                        values1, radius, sample)

    # ball_query's SYCL implementation gathers matches via a parallel
    # work-group scan rather than a serial index-ascending scan (see
    # BallQuerySYCL.h); when more than `sample` points are within range, the
    # nsample-sized subset kept (and the value duplicated to pad when fewer
    # than `sample` points are in range) can validly differ from a fixed
    # reference file generated by the old index-ascending algorithm, so
    # verify correctness directly against the input point clouds instead of
    # comparing to that reference: for each (batch, query) row, (a) every
    # returned candidate index is truly within `radius` of the query point,
    # and (b) the number of *distinct* candidate indices returned equals
    # min(sample, true in-range neighbor count) -- i.e. as many distinct
    # in-range neighbors as fit, with the rest being valid duplicate padding.
    batch, _, _ = values0.shape
    _, num_queries, _ = values1.shape
    ans = ans.reshape(batch, num_queries, sample)
    radius2 = radius * radius
    for b in range(batch):
        candidates = values0[b]  # [num_candidates, 3]
        queries = values1[b]  # [num_queries, 3]
        # [num_queries, num_candidates] squared distances.
        dist2 = np.sum((queries[:, None, :] - candidates[None, :, :])**2,
                       axis=-1)
        in_range_counts = np.sum(dist2 < radius2, axis=1)
        for q in range(num_queries):
            row = ans[b, q]
            if in_range_counts[q] == 0:
                # No candidate is within radius: the output holds whatever
                # placeholder value the caller's zero-initialized tensor had
                # (index 0), which is not a real neighbor -- nothing else to
                # verify for this query.
                continue
            in_range_mask = dist2[q, row] < radius2
            assert np.all(in_range_mask), (
                f"batch={b}, query={q}: returned index {row[~in_range_mask]}"
                f" is not within radius {radius}")
            distinct_count = len(set(row.tolist()))
            expected_count = min(sample, in_range_counts[q])
            assert distinct_count == expected_count, (
                f"batch={b}, query={q}: got {distinct_count} distinct "
                f"neighbors, expected {expected_count}")
