# Set common Open3D package metadata
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../../../cmake")
message(STATUS CMAKE_MODULE_PATH: ${CMAKE_MODULE_PATH})
include(Open3DPackaging)
string(TOLOWER ${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR} _sys)
set(CPACK_PACKAGE_FILE_NAME
    "${TARGET_NAME}-${_sys}-${OPEN3D_VERSION_FULL}")
set(CPACK_STRIP_FILES ON)
set(CPACK_PACKAGE_EXECUTABLES "${TARGET_NAME}")
set(CPACK_GENERATOR WIX)   # MSI installer files
set(CPACK_WIX_PATCH_FILE "${CMAKE_CURRENT_SOURCE_DIR}/file_association.wix.xml")
# set(CPACK_WIX_PRODUCT_ICON ${CPACK_PACKAGE_ICON})
include(CPack)
