# Open3D Docker test image:
# - based on Ubuntu 16.04
# - no Open3D dependencies are installed

FROM open3d-test:16.04-base

# install native python3
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel && \
    rm -rf /var/lib/apt/lists/*
