# Open3D Docker test image:
# - based on Ubuntu 16.04
# - no Open3D dependencies are installed

FROM open3d-test:16.04-base

# the miniconda2/3 installer filename
ARG MC_INSTALLER
COPY /setup/$MC_INSTALLER .

# miniconda2/3 install dir
ARG CONDA_DIR
ENV PATH "$CONDA_DIR"/bin:$PATH

# miniconda:
# - install
# - install conda-build & conda-verify
# - update
# - clean
# - enable the 'conda' command
# - activate
RUN /bin/bash /root/$MC_INSTALLER -bfp "$CONDA_DIR" && \
    rm -rf /root/$MC_INSTALLER && \
    conda install -qy conda-build conda-verify && \
    conda update --all -qy && \
    conda config --set auto_update_conda False && \
    conda clean -aqy && \
    ln -s "$CONDA_DIR/etc/profile.d/conda.sh" /etc/profile.d/conda.sh && \
    echo ". $CONDA_DIR/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc
