ARG UBUNTU_VERSION

FROM open3d-test:${UBUNTU_VERSION}-deps

# install Open3D dependencies
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
    libeigen3-dev \
    libglew-dev \
    libglfw3-dev \
    libjpeg-dev \
    libjsoncpp-dev \
    libpng-dev && \
    rm -rf /var/lib/apt/lists/*
