# Open3D Docker test image:
# - based on Ubuntu 16.04
# - Open3D dependencies are installed here

FROM open3d-test:16.04-deps

# install python2 dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python-dev \
    python-pip \
    python-setuptools \
    python-wheel && \
    rm -rf /var/lib/apt/lists/*
