ARG UBUNTU_VERSION

FROM open3d-test:${UBUNTU_VERSION}-deps

ARG MC_INSTALLER
ARG CONDA_DIR

# the miniconda2/3 installer filename
COPY /setup/${MC_INSTALLER} .

# miniconda:
# - install
# - install conda-build & conda-verify
# - update
# - clean
# - enable the 'conda' command
# - activate
RUN /bin/bash "/root/${MC_INSTALLER}" -bfp "${CONDA_DIR}" && \
    rm -rf "/root/${MC_INSTALLER}" && \
    "${CONDA_DIR}/bin/conda" install -qy conda-build conda-verify && \
    "${CONDA_DIR}/bin/conda" update --all -qy && \
    "${CONDA_DIR}/bin/conda" config --set auto_update_conda False && \
    "${CONDA_DIR}/bin/conda" clean -aqy && \
    ln -s "${CONDA_DIR}/etc/profile.d/conda.sh" /etc/profile.d/conda.sh && \
    echo ". ${CONDA_DIR}/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate" >> ~/.bashrc
