# Open3D Docker test image:
# - based on Ubuntu 18.04
# - Open3D dependencies are installed here

FROM open3d-test:18.04-deps

COPY /setup/Miniconda3-latest-Linux-x86_64.sh .

# install miniconda3
RUN chmod a+x /root/Miniconda3-latest-Linux-x86_64.sh && \
    /root/Miniconda3-latest-Linux-x86_64.sh -b && \
    rm -rf /root/Miniconda3-latest-Linux-x86_64.sh && \
    /root/miniconda3/bin/conda install -q -y -c anaconda conda-build && \
    /root/miniconda3/bin/conda install -q -y -c anaconda conda-verify && \
    /root/miniconda3/bin/conda clean -a -q -y
