# Open3D Docker test image:
# - based on Ubuntu 18.04
# - no Open3D dependencies are installed

FROM open3d-test:18.04-base

# install python3 dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel && \
    rm -rf /var/lib/apt/lists/*
