# Open3D Docker test image:
# - based on Ubuntu 18.04
# - no Open3D dependencies are installed

FROM open3d-test:18.04-base

COPY /setup/Miniconda2-latest-Linux-x86_64.sh .

# install miniconda2
RUN chmod a+x /root/Miniconda2-latest-Linux-x86_64.sh && \
    /root/Miniconda2-latest-Linux-x86_64.sh -b && \
    rm -rf /root/Miniconda2-latest-Linux-x86_64.sh && \
    /root/miniconda2/bin/conda install -q -y conda-build conda-verify && \
    /root/miniconda2/bin/conda update --all -q -y && \
    /root/miniconda2/bin/conda clean -a -q -y
