# Open3D Docker test image:
# - based on Ubuntu 18.04
# - no Open3D dependencies are installed

FROM open3d-test:18.04-base

ARG PYTHON

# install native python
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
    ${PYTHON}-dev \
    ${PYTHON}-pip \
    ${PYTHON}-setuptools \
    ${PYTHON}-wheel && \
    rm -rf /var/lib/apt/lists/*
