ARG UBUNTU_VERSION
ARG PYTHON

FROM open3d-test:${UBUNTU_VERSION}-deps

# install native python
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
    ${PYTHON}-dev \
    ${PYTHON}-pip \
    ${PYTHON}-setuptools \
    ${PYTHON}-wheel && \
    rm -rf /var/lib/apt/lists/*
