FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

# install Open3D dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    libglu1-mesa-dev \
    python3-dev \
    libxrandr-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxi-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root

COPY /setup/install-gtest.sh .
RUN chmod a+x /root/install-gtest.sh

COPY /setup/googletest-release-1.8.0.tar.gz .
