FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

# install Open3D dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    apt-utils \
    build-essential \
    cmake \
    git \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglu1-mesa-dev \
    libosmesa6-dev \
    python3 \
    python3-dev \
    python3-pip \
    python3-tk \
    software-properties-common \
    xorg-dev \
    wget && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip
RUN pip3 install matplotlib numpy

WORKDIR /root

COPY ./setup/install-gtest.sh .
RUN chmod a+x /root/install-gtest.sh
RUN /root/install-gtest.sh
