// ----------------------------------------------------------------------------
// -                        Open3D: www.open3d.org                            -
// ----------------------------------------------------------------------------
// Copyright (c) 2018-2023 www.open3d.org
// SPDX-License-Identifier: MIT
// ----------------------------------------------------------------------------

#include "open3d/core/Indexer.isph"
#include "open3d/utility/Helper.isph"

OPEN3D_ENSURE_EXPORTED(Indexer)
OPEN3D_ENSURE_EXPORTED(TensorRef)
