rm -rf build/
rm -rf dist/
rm -rf *.egg-info/
rm -rf open3d/__init__.pyc
rm -rf open3d/__pycache__
rm -rf open3d/linux/__init__.pyc
rm -rf open3d/linux/__pycache__
rm -rf open3d/macos/__init__.pyc
rm -rf open3d/macos/__pycache__
rm -rf open3d/win32/__init__.pyc
rm -rf open3d/win32/__pycache__
