# Open3D Docker test image:
# - based on Ubuntu 14.04
# - no Open3D dependencies are installed

FROM open3d-test:14.04-base

COPY /setup/Miniconda3-latest-Linux-x86_64.sh .

# install miniconda3
RUN chmod a+x /root/Miniconda3-latest-Linux-x86_64.sh && \
    /root/Miniconda3-latest-Linux-x86_64.sh -b && \
    rm -rf /root/Miniconda3-latest-Linux-x86_64.sh && \
    /root/miniconda3/bin/conda install -q -y conda-build conda-verify && \
    /root/miniconda3/bin/conda update --all -q -y && \
    /root/miniconda3/bin/conda clean -a -q -y
