# Open3D Docker test image:
# - based on Ubuntu 14.04
# - no Open3D dependencies are installed

FROM open3d-test:14.04-base

# install native python2
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
    python-dev \
    python-pip \
    python-setuptools \
    python-wheel && \
    rm -rf /var/lib/apt/lists/*
