ARG UBUNTU_VERSION

FROM open3d-test:${UBUNTU_VERSION}-${BUNDLE_TYPE}

ARG PYTHON

# install native python
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
    ${PYTHON}-dev \
    ${PYTHON}-pip \
    ${PYTHON}-setuptools \
    ${PYTHON}-wheel && \
    rm -rf /var/lib/apt/lists/*
