# Open3D Docker base image doesn't install Python or Open3D dependencies.
# - xorg-dev replaced with just 4 out of ~60 dependencies:
#   - libxrandr-dev
#   - libxinerama-dev
#   - libxcursor-dev
#   - libxi-dev &&
# - by replacing xorg-dev we're:
#   - reducing image size substantially
#   - making sure libpng is not installed

ARG UBUNTU_VERSION

FROM ubuntu:${UBUNTU_VERSION}

ENV DEBIAN_FRONTEND noninteractive

# install Open3D dependencies
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
    build-essential \
    cmake3 \
    git \
    libglu1-mesa-dev \
    libxrandr-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxi-dev \
    tzdata && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root

COPY /setup/googletest-release-1.8.0.tar.gz .
COPY /setup/install-gtest.sh .
COPY /setup/test.sh .

# install googletest
# work around SSL CA cert issue...
RUN /bin/bash /root/install-gtest.sh && \
    rm /root/install-gtest.sh && \
    git config --global http.sslVerify false
