# Open3D Docker test image:
# - based on Ubuntu 14.04
# - no Open3D dependencies are installed

FROM open3d-test:14.04-base

# install python2 dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget && \
    rm -rf /var/lib/apt/lists/* && \
    wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh && \
    chmod a+x /root/Miniconda2-latest-Linux-x86_64.sh && \
    /root/Miniconda2-latest-Linux-x86_64.sh -b && \
    rm -rf /root/Miniconda2-latest-Linux-x86_64.sh && \
    /root/miniconda2/bin/conda install -y -c anaconda conda-build && \
    /root/miniconda2/bin/conda install -y -c anaconda conda-verify && \
    /root/miniconda2/bin/conda clean -a
