# Open3D Docker test image:
# - based on Ubuntu 14.04
# - Open3D dependencies are installed here

FROM open3d-test:14.04-deps

ARG PYTHON

# install native python
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
    ${PYTHON}-dev \
    ${PYTHON}-pip \
    ${PYTHON}-setuptools \
    ${PYTHON}-wheel && \
    rm -rf /var/lib/apt/lists/*
