# Open3D Docker test image:
# - based on Ubuntu 14.04
# - Open3D dependencies are installed here

FROM open3d-test:14.04-deps

# install native python3
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel && \
    rm -rf /var/lib/apt/lists/*
