_build_config = {
    "BUILD_TENSORFLOW_OPS" : False,
    "BUILD_PYTORCH_OPS" : False,
    "BUILD_CUDA_MODULE" : False,
    "BUILD_AZURE_KINECT" : False,
    "BUILD_LIBREALSENSE" : False,
    "BUILD_SHARED_LIBS" : False,
    "BUILD_GUI" : True,
    "BUILD_RPC_INTERFACE": False,
    "ENABLE_HEADLESS_RENDERING" : False,
    "BUILD_JUPYTER_EXTENSION" : False,
    "BUNDLE_OPEN3D_ML" : False,
    "GLIBCXX_USE_CXX11_ABI" : False,
    "CMAKE_BUILD_TYPE" : "Release",
    "CUDA_VERSION" : "",
    "CUDA_GENCODES" : "",
    "Tensorflow_VERSION" : "",
    "Pytorch_VERSION" : "",
    "WITH_OPENMP" : True,
}
