# Open3D Docker base image doesn't install Python or Open3D dependencies.
# - xorg-dev replaced with just 4 out of ~60 dependencies:
#   - libxrandr-dev
#   - libxinerama-dev
#   - libxcursor-dev
#   - libxi-dev &&
# - by replacing xorg-dev we're:
#   - reducing image size substantially
#   - making sure libpng is not installed

ARG UBUNTU_VERSION

FROM ubuntu:${UBUNTU_VERSION}

ARG UBUNTU_VERSION

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /root

COPY [ "/setup/googletest-release-1.8.0.tar.gz", \
       "/setup/install-gtest.sh", \
       "/setup/test.sh", \
       "./" ]

# install minimal Open3D dependencies
# install googletest, work around SSL CA cert issue...
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
    build-essential \
    git \
    libglu1-mesa-dev \
    libxrandr-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxi-dev \
    tzdata && \
    if [ "${UBUNTU_VERSION}" = "14.04" ]; then \
        apt-get install -qq -y --no-install-recommends cmake3; \
    else \
        apt-get install -qq -y --no-install-recommends cmake; \
    fi && \
    /bin/bash /root/install-gtest.sh && \
    git config --global http.sslVerify false && \
    rm /root/install-gtest.sh && \
    rm -rf /var/lib/apt/lists/*
